modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="torve"
version="1.0.0"
displayName="torve"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="fazer"

[[dependencies.torve]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



